[[headers]]
  for = "/*"
    [headers.values]
      Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "*.js"
    [headers.values]
      Content-Type = "application/javascript" # or "text/javascript"

[[headers]]
  for = "*.ttf" # For your font
    [headers.values]
      Content-Type = "font/ttf"